### ISSUE TITLE
Purpose?

### ISSUE THREAD

**Issue by iamjoshua** [nkalupahana/capacitor-cloudkit#1]
This seems to be the only cloudkit plugin for capacitor, but it doesn't actually utilize cloudkit beyond authentication. What is the use case for this?

**Comment by nkalupahana** [comment]
The purpose is just authentication -- namely, getting a ckWebAuthToken for a user account. For my use case, I use this token in other parts of my application to access [CloudKit via their REST API](https://github.com/nkalupahana/baseline/blob/main/functions/src/index.ts#L634), which is good enough for me. If you'd like to add methods to make specific types of requests to make it easier on the user of the plugin, though, go for it! (Or if you need a specific use case, I'm happy to take a look as well.) Until then, though, you're right -- authentication and getting that token for use elsewhere is all this plugin does, since it's all I needed for my application.

**Comment by iamjoshua** [comment]
Interesting. It might be a good idea to modify the repo name accordingly to something like capacitor-cloudkit-auth. This is still very useful though, so thank you for publishing! Additionally it could be even better to extend beyond auth by simply creating a dumb wrapper around the REST API. I wonder why no one has attempted this since the cordova days...

**Comment by nkalupahana** [comment]
Yeah! We'll see if anyone adds that functionality. I think I'll keep the name like this for now in case that functionality is added.
